version: "3"
services:
  my-test:
    image: nginx:1.17.1
    restart: always
    ports:
      - "7799:80"
    volumes:
      - ./dist/:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./variables.js:/usr/share/nginx/html/variables.js
